FROM node:18 AS build

WORKDIR /app

COPY serv/package.json serv/package-lock.json ./
RUN npm install

COPY serv/ ./

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
