FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

COPY demo/pom.xml .

RUN mvn dependency:go-offline

COPY demo/src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
